### ISSUE TITLE
Zinit is not dead!

### ISSUE THREAD

**Issue by pschmitt** [mattmc3/zsh_unplugged#1]
*Disclaimer: member of the zdharma-continuum org here.*

Sure there was some downtime due to the deletetening but we've kept zinit alive.

Several people stepped up to help restore what seemed lost and we've pretty much up and running again. Support and development continues. Zinit is not dead.

https://github.com/zdharma-continuum/zinit

**Comment by mattmc3** [comment]
@pschmitt - Thank you! The work you and @alichtman and others did to keep the Zdharma org from disappearing into the ether is so appreciated. I've updated this site's README to reflect an "Alive" project status and added a shoutout to the good work of those with zdharma-continuum. Is there anything else you'd like me to add?

**Comment by pschmitt** [comment]
You're welcome! Thanks for the mention :)
I see nothing else to be added. 🎩

**Comment by bew** [comment]
What about `zi` ?
https://github.com/z-shell/zi

It looks like the same thing as the old zinit

**Comment by mattmc3** [comment]
@bew - zi looks to have been started on 2021-11-11 (https://github.com/z-shell/zi/tree/bc1904dbe434e9bd3a95fe56b023bd8bd6189a51), a few days after this project. It might have some of the same features as zinit, but doesn't appear to share the same codebase. Still, zsh_unplugged is not intended to keep track of or highlight every new plugin manager that appears on the scene. It's purpose is solely to show how a simple ~20 line function can do much of the same work.
