### ISSUE TITLE
Running offline

### ISSUE THREAD

**Issue by dfarnand** [mattmc3/zsh_unplugged#10]
I love the simplicity of this system and I've been using it for a few months now! However the other day I was using my computer offline on an airplane, and when I opened a terminal I had to wait very long time for all the git commands to time out. 

I'm not sure if there would be a recommended git setting or some change to the plugin loading function that would skip the git timeout if there's no connection?

**Comment by mattmc3** [comment]
Awesome! I too love the simplicity of this setup. But of course as the author of [antidote](https://github.com/mattmc3/antidote), I have to spend a lot of time on the plugin manager side of the house. But for new installs, I grab-and-go this function from a gist, and it always brings me joy to use simple tools for simple problems.

On to your question - my quick google search turned up this https://stackoverflow.com/questions/6458790/is-there-a-way-to-make-git-over-http-timeout

If you config git with these two options, it'll time out sooner when there's no connection. Hope that helps.
