### ISSUE TITLE
plugin-compile:4: no matches found: ~/.zsh/plugins/**/*.zsh-theme

### ISSUE THREAD

**Issue by 404cn** [mattmc3/zsh_unplugged#2]
I just copy the example file and delete pure prompt theme and run `plugin-compile`

**Comment by mattmc3** [comment]
Thanks! Good catch. I was missing the NULL_GLOB qualifier (N) on the pattern (https://zsh.sourceforge.io/Doc/Release/Expansion.html#Glob-Qualifiers). I've updated the code. It should be:

```shell
# if you want to compile your plugins you may see performance gains
function plugin-compile () {
  local plugindir="${ZPLUGINDIR:-$HOME/.zsh/plugins}"
  autoload -U zrecompile
  local f
  for f in $plugindir/**/*.zsh{,-theme}(N); do
    zrecompile -pq "$f"
  done
```
