### ISSUE TITLE
cannot find init file for powerlevel10k

### ISSUE THREAD

**Issue by wang1zhen** [mattmc3/zsh_unplugged#5]
After the recent update, zsh_unplugged cannot automatically find the init file for `romkatv/powerlevel10k`

```
Plugin has no init file 'romkatv/powerlevel10k'.
```

The init file for powerlevel10k should be `powerlevel10k.zsh-theme`, maybe adding `.zsh-theme` could fix this.

**Comment by mattmc3** [comment]
Thank you! This is resolved. I'll add unit tests today to make sure future changes do not break things like this again so that you and others can safely rely on this project to work for you going forward.

**Comment by mattmc3** [comment]
ZTAP tests have been added. If there are other plugins that have issues, let me know and I'll add a unit test for them.
