### ISSUE TITLE
ln: failed to create symbolic link

### ISSUE THREAD

**Issue by EtherealMochi** [mattmc3/zsh_unplugged#7]
Hello! I am using your plugin-load function and I have run into an issue. I think I know where it is, but I don't know how to fix it as I am very new to ZSH. I am using chezmoi to keep all my ZSH configs the same across all of my machines. Upon initial load of zsh, there are no issues and plugins load with no problem. When copying my configs to a different machine and running zsh I get a few issues with certain plugins. The output is below: 

```zsh
ln: failed to create symbolic link '/config/.config/zsh/plugins/powerlevel10k/powerlevel10k.plugin.zsh': File exists
ln: failed to create symbolic link '/config/.config/zsh/plugins/z/z.plugin.zsh': File exists
ln: failed to create symbolic link '/config/.config/zsh/plugins/zsh-tailf/zsh-tailf.plugin.zsh': File exists
ln: failed to create symbolic link '/config/.config/zsh/plugins/up.zsh/up.zsh.plugin.zsh': File exists
```

Since the links were already created before and currently exist, why is the plugin-load function still trying to create the symbolic links? I realize that I can delete the plugin folders or delete the symbolic link that was created to get it to work on the machine I pulled my dotfiles into.  It seems that the plugin load function is making symbolic links when it does not need to also, as a few of those particular plugins already come with the correct files. I have listed the default files that come with the plugins below:

https://github.com/peterhurford/up.zsh includes the file:     _**up.plugin.zsh**_
https://github.com/rummik/zsh-tailf includes the file:      _**tailf.plugin.zsh**_

From what I can gather, the plugin-load function thinks there are no plugin files and wants to create symbolic link because the plugin files do not contain the full repo names (up.zsh. zsh-tailf). 

edit: I realize this post is kind of all over the place, sorry.

**Comment by mattmc3** [comment]
Interesting. This is the relevant code block:

https://github.com/mattmc3/zsh_unplugged/blob/6c336f439f6dde460f2ce3838c69a7bcfaf3d265/zsh_unplugged.plugin.zsh#L17-L21

It tests for the existence of the init file prior to creating a symlink (`if [[ ! -e $initfile ]]; then`). You might try adding an `echo` statement to help debug and get the values of the variables in question: `echo initfile=$initfile plugin_dir=$plugin_dir` and let me know what you find.

**Comment by EtherealMochi** [comment]
> Interesting. This is the relevant code block:
> 
> https://github.com/mattmc3/zsh_unplugged/blob/6c336f439f6dde460f2ce3838c69a7bcfaf3d265/zsh_unplugged.plugin.zsh#L17-L21
> 
> It tests for the existence of the init file prior to creating a symlink (`if [[ ! -e $initfile ]]; then`). You might try adding an `echo` statement to help debug and get the values of the variables in question: `echo initfile=$initfile plugin_dir=$plugin_dir` and let me know what you find.

Okay after doing some more researching I figured out what the issue is in my case. On my main machine it creates the symbolic links with the full path. When I use chezmoi to pull my config to my other machines it pulls those symbolic links as well but they are broken. Somehow that was causing the function to not see any symlinks. I corrected this by changing line 20 to use relative paths instead of absolute. Now it is working on all my machines with no errors. 

`ln -sr "${initfiles[1]}" "$initfile"`

**Comment by mattmc3** [comment]
Clever! The BSD `ln` that ships with MacOS doesn't have the `-r` option, so I can't incorporate that or I'd have to have everyone on MacOS `brew install coreutils`, so for now we'll just mark this is resolved.

**Comment by EtherealMochi** [comment]
@mattmc3  I completely understand and I have no problem with doing the change on my end only. Thanks for working with me today.
